const clean=(v='',m=1000)=>String(v??'').trim().slice(0,m);const array=v=>Array.isArray(v)?v:[];const money=v=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
function fail(message,statusCode=400,code='ERP_FINANCE_ERROR'){const e=new Error(message);e.statusCode=statusCode;e.code=code;return e}
function actorName(a={}){return clean(a.name||a.email||'Operador',160)}
export function createErpFinanceService(context={}){
 const {Order,IntegrationAuditLog,toJSON,redact}=context;if(!Order)throw new Error('[erp-finance] Order não informado');
 const serial=d=>typeof toJSON==='function'?toJSON(d):(d?.toObject?d.toObject():d);
 async function findOrder(id){let o=null;try{o=await Order.findById(id)}catch{}if(!o||o.origin!=='erp_ariana')throw fail('Venda do Ariana ERP não encontrada.',404,'ERP_ORDER_NOT_FOUND');return o}
 async function audit(type,o,metadata={}){if(!IntegrationAuditLog)return;try{await IntegrationAuditLog.create({scope:'erp_ariana',eventType:type,orderId:String(o?._id||''),status:o?.status||'',message:clean(metadata.message||'',1000),metadata:redact?redact(metadata):metadata})}catch(e){console.warn('[erp-finance/audit]',e.message)}}
 async function list(query={}){const filter={origin:'erp_ariana','televendas.erp.financialStatus':{$in:['generated','partial','settled','reversed']}};const orders=await Order.find(filter).sort({updatedAt:-1}).limit(500);let rows=[];for(const order of orders){const erp=order.televendas?.erp||{};for(const r of array(erp.receivables)){rows.push({orderId:String(order._id),code:erp.code||String(order._id).slice(-8).toUpperCase(),customerName:order.customerName||'Consumidor',customerCpf:order.customerCpf||'',customerPhone:order.customerPhone||'',number:Number(r.number||1),installments:Number(r.installments||1),value:money(r.value),dueAt:r.dueAt,status:r.status||'pendente',method:r.method||order.payment?.method||'',receivedAt:r.receivedAt||null,receivedAmount:money(r.receivedAmount??(r.status==='recebido'?r.value:0)),orderTotal:money(order.total)})}}
 const q=clean(query.q||query.search||'',140).toLowerCase();if(q)rows=rows.filter(r=>[r.code,r.customerName,r.customerCpf,r.customerPhone,r.method].join(' ').toLowerCase().includes(q));if(query.status&&query.status!=='all')rows=rows.filter(r=>r.status===query.status);rows.sort((a,b)=>new Date(a.dueAt||0)-new Date(b.dueAt||0));const totalPending=money(rows.filter(r=>r.status==='pendente').reduce((s,r)=>s+r.value,0)),totalReceived=money(rows.filter(r=>r.status==='recebido').reduce((s,r)=>s+(r.receivedAmount||r.value),0)),overdue=rows.filter(r=>r.status==='pendente'&&r.dueAt&&new Date(r.dueAt)<new Date()).length;return{receivables:rows,summary:{count:rows.length,totalPending,totalReceived,overdue}}}
 async function receive(orderId,number,payload={},actor={}){const order=await findOrder(orderId);if(order.status!=='faturado')throw fail('Somente venda faturada pode receber parcela.',409,'ORDER_NOT_BILLED');const erp=order.televendas?.erp||{},receivables=array(erp.receivables).map(r=>({...r})),n=Math.max(1,Number(number||0)),idx=receivables.findIndex(r=>Number(r.number)===n);if(idx<0)throw fail('Parcela não encontrada.',404,'RECEIVABLE_NOT_FOUND');if(receivables[idx].status==='recebido')throw fail('Esta parcela já foi recebida.',409,'ALREADY_RECEIVED');if(['cancelado','estornado'].includes(receivables[idx].status))throw fail('Esta parcela está cancelada/estornada.',409,'RECEIVABLE_CLOSED');const expected=money(receivables[idx].value),received=money(payload.amount??payload.value??expected);if(received<=0)throw fail('Valor recebido inválido.',400,'INVALID_AMOUNT');receivables[idx]={...receivables[idx],status:'recebido',receivedAt:new Date(),receivedAmount:received,receivedMethod:clean(payload.method||payload.paymentMethod||receivables[idx].method||order.payment?.method||'',80),receiptNote:clean(payload.note||payload.notes||'',1000),receivedBy:actorName(actor)};const all=receivables.every(r=>r.status==='recebido');order.paymentStatus=all?'approved':'partial';order.payment={...(order.payment||{}),status:all?'approved':'partial',received:all,receivedAt:all?new Date():order.payment?.receivedAt};order.televendas={...(order.televendas||{}),erp:{...erp,receivables,financialStatus:all?'settled':'partial',financialSettledAt:all?new Date():null,timeline:[...array(erp.timeline),{status:'recebimento',label:`Parcela ${n}/${receivables[idx].installments} recebida - ${money(received).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}`,at:new Date(),by:actorName(actor)}]}};await order.save();await audit('erp.receivable.received',order,{message:`Parcela ${n} recebida`,number:n,amount:received});return{order:serial(order),receivable:receivables[idx]}}
 return{list,receive}
}
export default createErpFinanceService;
