import mongoose from 'mongoose';

const clean=(v='',m=1000)=>String(v??'').trim().slice(0,m);
const money=(v=0)=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
function fail(message,statusCode=400,code='ERP_LEDGER_ERROR'){const e=new Error(message);e.statusCode=statusCode;e.code=code;return e}
function actorName(a={}){return clean(a.name||a.nome||a.email||'Operador',180)}
const base={timestamps:true,versionKey:false,minimize:false};

const categorySchema=new mongoose.Schema({name:{type:String,required:true,index:true},type:{type:String,enum:['receita','despesa'],required:true,index:true},active:{type:Boolean,default:true},system:{type:Boolean,default:false}},base);
categorySchema.index({name:1,type:1},{unique:true});
const bankSchema=new mongoose.Schema({name:{type:String,required:true,index:true},bank:String,agency:String,account:String,type:{type:String,default:'corrente'},openingBalance:{type:Number,default:0},currentBalance:{type:Number,default:0},active:{type:Boolean,default:true},notes:String},base);
const entrySchema=new mongoose.Schema({direction:{type:String,enum:['receivable','payable'],required:true,index:true},personName:{type:String,required:true,index:true},personDocument:String,description:String,categoryId:String,categoryName:String,bankAccountId:String,bankAccountName:String,paymentMethod:String,value:{type:Number,required:true},advance:{type:Number,default:0},competenceAt:{type:Date,required:true,index:true},dueAt:{type:Date,required:true,index:true},status:{type:String,enum:['pending','paid','cancelled'],default:'pending',index:true},paidAt:Date,paidValue:{type:Number,default:0},notes:String,origin:{type:String,default:'manual',index:true},orderId:String,createdBy:String,paidBy:String,cancelledAt:Date,cancelledBy:String},base);
entrySchema.index({direction:1,status:1,dueAt:1});
const Category=mongoose.models.ErpAccountCategory||mongoose.model('ErpAccountCategory',categorySchema);
const Bank=mongoose.models.ErpBankAccount||mongoose.model('ErpBankAccount',bankSchema);
const Entry=mongoose.models.ErpFinancialEntry||mongoose.model('ErpFinancialEntry',entrySchema);

const defaults=[['Vendas','receita'],['Recebimentos diversos','receita'],['Compras de mercadorias','despesa'],['Despesas operacionais','despesa'],['Fretes','despesa'],['Impostos','despesa'],['Pessoal','despesa']];

export function createErpLedgerService(context={}){
 const {IntegrationAuditLog,redact}=context;
 async function audit(eventType,metadata={}){if(!IntegrationAuditLog)return;try{await IntegrationAuditLog.create({scope:'erp_ariana',eventType,status:clean(metadata.status||'',80),message:clean(metadata.message||'',1000),metadata:redact?redact(metadata):metadata})}catch(e){console.warn('[erp-ledger/audit]',e.message)}}
 async function ensureDefaults(){for(const [name,type] of defaults){await Category.updateOne({name,type},{$setOnInsert:{name,type,active:true,system:true}},{upsert:true})}}
 const serial=d=>d?.toObject?d.toObject():d;
 async function categories(query={}){await ensureDefaults();const filter={};if(query.type&&['receita','despesa'].includes(query.type))filter.type=query.type;if(query.active!=='all')filter.active={$ne:false};return (await Category.find(filter).sort({type:1,name:1})).map(serial)}
 async function createCategory(payload={},actor={}){const name=clean(payload.name,160),type=clean(payload.type,20);if(!name||!['receita','despesa'].includes(type))throw fail('Nome e tipo da categoria são obrigatórios.');try{const row=await Category.create({name,type,active:true,system:false});await audit('erp.ledger.category.created',{message:`Categoria ${name} criada`,categoryId:String(row._id),by:actorName(actor)});return serial(row)}catch(e){if(e?.code===11000)throw fail('Já existe uma categoria com este nome e tipo.',409,'CATEGORY_EXISTS');throw e}}
 async function updateCategory(id,payload={},actor={}){const row=await Category.findById(id);if(!row)throw fail('Categoria não encontrada.',404);if(payload.name!==undefined)row.name=clean(payload.name,160)||row.name;if(payload.active!==undefined)row.active=Boolean(payload.active);if(payload.type!==undefined&&['receita','despesa'].includes(payload.type))row.type=payload.type;await row.save();await audit('erp.ledger.category.updated',{message:`Categoria ${row.name} atualizada`,categoryId:String(row._id),by:actorName(actor)});return serial(row)}
 async function banks(query={}){const filter={};if(query.active!=='all')filter.active={$ne:false};return (await Bank.find(filter).sort({name:1})).map(serial)}
 async function createBank(payload={},actor={}){const name=clean(payload.name,180);if(!name)throw fail('Informe o nome da conta bancária.');const opening=money(payload.openingBalance||0);const row=await Bank.create({name,bank:clean(payload.bank,120),agency:clean(payload.agency,80),account:clean(payload.account,100),type:clean(payload.type||'corrente',60),openingBalance:opening,currentBalance:opening,active:true,notes:clean(payload.notes,1000)});await audit('erp.ledger.bank.created',{message:`Conta ${name} criada`,bankAccountId:String(row._id),openingBalance:opening,by:actorName(actor)});return serial(row)}
 async function updateBank(id,payload={},actor={}){const row=await Bank.findById(id);if(!row)throw fail('Conta bancária não encontrada.',404);for(const k of ['name','bank','agency','account','type','notes'])if(payload[k]!==undefined)row[k]=clean(payload[k],k==='notes'?1000:180);if(payload.active!==undefined)row.active=Boolean(payload.active);await row.save();await audit('erp.ledger.bank.updated',{message:`Conta ${row.name} atualizada`,bankAccountId:String(row._id),by:actorName(actor)});return serial(row)}
 async function resolveCategory(id,direction){if(!id)return null;const row=await Category.findById(id);if(!row||row.active===false)throw fail('Categoria financeira inválida.',409);const expected=direction==='receivable'?'receita':'despesa';if(row.type!==expected)throw fail(`Use uma categoria do tipo ${expected}.`,409,'CATEGORY_TYPE_MISMATCH');return row}
 async function resolveBank(id){if(!id)return null;const row=await Bank.findById(id);if(!row||row.active===false)throw fail('Conta bancária inválida ou inativa.',409);return row}
 async function createEntry(direction,payload={},actor={}){if(!['receivable','payable'].includes(direction))throw fail('Tipo de lançamento inválido.');const personName=clean(payload.personName||payload.payer||payload.receiver,200);if(!personName)throw fail(direction==='payable'?'Informe o recebedor.':'Informe o pagador.');const value=money(payload.value);if(value<=0)throw fail('Informe um valor maior que zero.');const competenceAt=new Date(payload.competenceAt||payload.competenceDate||new Date());const dueAt=new Date(payload.dueAt||payload.dueDate||new Date());if(Number.isNaN(competenceAt.getTime())||Number.isNaN(dueAt.getTime()))throw fail('Data de competência ou vencimento inválida.');const category=await resolveCategory(payload.categoryId,direction);const bank=await resolveBank(payload.bankAccountId);const row=await Entry.create({direction,personName,personDocument:clean(payload.personDocument,60),description:clean(payload.description,500),categoryId:category?String(category._id):'',categoryName:category?.name||clean(payload.categoryName,160),bankAccountId:bank?String(bank._id):'',bankAccountName:bank?.name||'',paymentMethod:clean(payload.paymentMethod,80),value,advance:Math.max(0,money(payload.advance||0)),competenceAt,dueAt,status:'pending',notes:clean(payload.notes,2000),origin:clean(payload.origin||'manual',80),orderId:clean(payload.orderId,120),createdBy:actorName(actor)});await audit('erp.ledger.entry.created',{message:`${direction==='payable'?'Conta a pagar':'Conta a receber'} criada`,entryId:String(row._id),direction,value,by:actorName(actor)});if(payload.paid===true) return pay(String(row._id),payload,actor);return serial(row)}
 async function listEntries(query={}){const filter={};if(['receivable','payable'].includes(query.direction))filter.direction=query.direction;if(['pending','paid','cancelled'].includes(query.status))filter.status=query.status;if(query.from||query.to){filter.dueAt={};if(query.from)filter.dueAt.$gte=new Date(query.from);if(query.to){const d=new Date(query.to);d.setHours(23,59,59,999);filter.dueAt.$lte=d}}const q=clean(query.q||query.search,160);if(q){const rx=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');filter.$or=[{personName:rx},{description:rx},{categoryName:rx},{personDocument:rx}]}const limit=Math.min(1000,Math.max(1,Number(query.limit||500)));const rows=await Entry.find(filter).sort({dueAt:1,createdAt:-1}).limit(limit);return rows.map(serial)}
 async function pay(id,payload={},actor={}){const current=await Entry.findById(id);if(!current)throw fail('Lançamento não encontrado.',404);if(current.status==='paid')throw fail('Este lançamento já está pago/recebido.',409);if(current.status==='cancelled')throw fail('Lançamento cancelado não pode ser quitado.',409);const paidValue=money(payload.paidValue??payload.value??current.value);if(paidValue<=0)throw fail('Valor de quitação inválido.');const bankId=clean(payload.bankAccountId||current.bankAccountId,120);const bank=bankId?await resolveBank(bankId):null;const paidAt=new Date(payload.paidAt||new Date());if(Number.isNaN(paidAt.getTime()))throw fail('Data de pagamento inválida.');const updated=await Entry.findOneAndUpdate({_id:id,status:'pending'},{$set:{status:'paid',paidAt,paidValue,paidBy:actorName(actor),bankAccountId:bank?String(bank._id):current.bankAccountId,bankAccountName:bank?.name||current.bankAccountName,paymentMethod:clean(payload.paymentMethod||current.paymentMethod,80)}},{new:true});if(!updated)throw fail('O lançamento foi alterado por outro usuário. Atualize a tela.',409,'ENTRY_CHANGED');if(bank){const delta=updated.direction==='receivable'?paidValue:-paidValue;try{await Bank.updateOne({_id:bank._id},{$inc:{currentBalance:delta}})}catch(e){await Entry.updateOne({_id:id},{$set:{status:'pending',paidAt:null,paidValue:0,paidBy:''}});throw e}}await audit('erp.ledger.entry.paid',{message:`Lançamento quitado`,entryId:String(updated._id),direction:updated.direction,value:paidValue,bankAccountId:bank?String(bank._id):'',by:actorName(actor)});return serial(updated)}
 async function unpay(id,actor={}){const row=await Entry.findById(id);if(!row)throw fail('Lançamento não encontrado.',404);if(row.status!=='paid')throw fail('Somente lançamento quitado pode ser reaberto.',409);if(row.bankAccountId){const delta=row.direction==='receivable'?-money(row.paidValue||row.value):money(row.paidValue||row.value);await Bank.updateOne({_id:row.bankAccountId},{$inc:{currentBalance:delta}})}row.status='pending';row.paidAt=null;row.paidValue=0;row.paidBy='';await row.save();await audit('erp.ledger.entry.reopened',{message:'Lançamento reaberto',entryId:String(row._id),by:actorName(actor)});return serial(row)}
 async function cancel(id,actor={}){const row=await Entry.findById(id);if(!row)throw fail('Lançamento não encontrado.',404);if(row.status==='paid')throw fail('Reabra o lançamento antes de cancelar.',409);row.status='cancelled';row.cancelledAt=new Date();row.cancelledBy=actorName(actor);await row.save();await audit('erp.ledger.entry.cancelled',{message:'Lançamento cancelado',entryId:String(row._id),by:actorName(actor)});return serial(row)}
 async function report(query={}){const rows=await listEntries({...query,limit:1000});const active=rows.filter(r=>r.status!=='cancelled');const sum=(arr,field='value')=>money(arr.reduce((s,r)=>s+Number(r[field]||0),0));const rec=active.filter(r=>r.direction==='receivable'),payRows=active.filter(r=>r.direction==='payable'),recPaid=rec.filter(r=>r.status==='paid'),payPaid=payRows.filter(r=>r.status==='paid');return{receitaPrevista:sum(rec),receitaRealizada:sum(recPaid,'paidValue'),despesaPrevista:sum(payRows),despesaRealizada:sum(payPaid,'paidValue'),saldoPrevisto:money(sum(rec)-sum(payRows)),saldoRealizado:money(sum(recPaid,'paidValue')-sum(payPaid,'paidValue')),count:active.length}}
 return{categories,createCategory,updateCategory,banks,createBank,updateBank,createReceivable:(p,a)=>createEntry('receivable',p,a),createPayable:(p,a)=>createEntry('payable',p,a),listEntries,pay,unpay,cancel,report};
}
export default createErpLedgerService;
