import mongoose from 'mongoose';
const clean=(v='',m=500)=>String(v??'').trim().slice(0,m);
const money=v=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
const regexEscape=v=>String(v||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const sum=(a,f='value')=>money(a.reduce((s,x)=>s+Number(x[f]||0),0));
function dayStart(){const d=new Date();d.setHours(0,0,0,0);return d}
function dueView(r){if(r.status==='paid')return'paid';if(r.status==='cancelled')return'cancelled';return new Date(r.dueAt)<dayStart()?'overdue':'upcoming'}
function monthKey(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function reportPeriod(q={}){const now=new Date(),from=q.from?new Date(q.from):new Date(now.getFullYear(),0,1),to=q.to?new Date(q.to):new Date(now.getFullYear(),11,31,23,59,59,999);if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime()))throw Object.assign(new Error('Período inválido.'),{statusCode:400});from.setHours(0,0,0,0);to.setHours(23,59,59,999);return{from,to}}

export function createErpParityAnalyticsService(context={}){
 const {Order}=context;if(!Order)throw new Error('[erp-parity] Order não informado');
 async function currentReceivables(){const orders=await Order.find({origin:'erp_ariana',status:'faturado','televendas.erp.receivables.0':{$exists:true}}).select('_id customerName payment televendas updatedAt').lean(),out=[];for(const o of orders)for(const r of o.televendas?.erp?.receivables||[]){if(!['pendente','recebido'].includes(r.status))continue;out.push({id:`order:${o._id}:${r.number||out.length}`,source:'ariana_sale',origin:'ariana_sale',direction:'receivable',personName:o.customerName||'Consumidor',personDocument:'',description:o.televendas?.erp?.code||'Venda Ariana',categoryName:'Vendas',bankAccountName:'',paymentMethod:r.receivedMethod||r.method||o.payment?.method||'',value:Number(r.value||0),paidValue:r.status==='recebido'?Number(r.receivedAmount??r.value??0):0,status:r.status==='recebido'?'paid':'pending',dueAt:r.dueAt,competenceAt:o.updatedAt,paidAt:r.receivedAt||null,orderId:String(o._id)})}return out}
 async function finance(q={}){const Entry=mongoose.models.ErpFinancialEntry;if(!Entry)throw Object.assign(new Error('Financeiro ainda não inicializado.'),{statusCode:503});const filter={};if(['receivable','payable'].includes(q.direction))filter.direction=q.direction;if(q.origin)filter.origin=clean(q.origin,80);if(q.categoryId)filter.categoryId=clean(q.categoryId,120);if(q.bankAccountId)filter.bankAccountId=clean(q.bankAccountId,120);if(q.paymentMethod)filter.paymentMethod=clean(q.paymentMethod,100);if(q.from||q.to){filter.dueAt={};if(q.from)filter.dueAt.$gte=new Date(q.from);if(q.to){const d=new Date(q.to);d.setHours(23,59,59,999);filter.dueAt.$lte=d}}const text=clean(q.q||q.search,160);if(text){const rx=new RegExp(regexEscape(text),'i');filter.$or=[{personName:rx},{personDocument:rx},{description:rx},{categoryName:rx}]}let base=(await Entry.find(filter).sort({dueAt:1}).limit(30000).lean()).map(r=>({...r,id:String(r._id),source:r.origin==='sige_import'?'historico':'financeiro'}));if(!q.direction||q.direction==='receivable')base.push(...await currentReceivables());if(['receivable','payable'].includes(q.direction))base=base.filter(r=>r.direction===q.direction);if(q.from||q.to){const from=q.from?new Date(q.from):null,to=q.to?new Date(q.to):null;if(to)to.setHours(23,59,59,999);base=base.filter(r=>{const d=new Date(r.dueAt);return(!from||d>=from)&&(!to||d<=to)})}
  const active=base.filter(r=>r.status!=='cancelled'),rec=active.filter(r=>r.direction==='receivable'),pay=active.filter(r=>r.direction==='payable'),recPending=rec.filter(r=>r.status==='pending'),payPending=pay.filter(r=>r.status==='pending'),recOver=recPending.filter(r=>dueView(r)==='overdue'),payOver=payPending.filter(r=>dueView(r)==='overdue'),recUpcoming=recPending.filter(r=>dueView(r)==='upcoming'),payUpcoming=payPending.filter(r=>dueView(r)==='upcoming'),recPaid=rec.filter(r=>r.status==='paid'),payPaid=pay.filter(r=>r.status==='paid');const bucket=a=>({count:a.length,value:sum(a)});
  const dm=new Map();for(const r of recOver){const k=(r.personDocument||r.personName||'sem-identificacao').toLowerCase(),x=dm.get(k)||{personName:r.personName||'Sem identificação',personDocument:r.personDocument||'',count:0,total:0,oldestDue:r.dueAt};x.count++;x.total+=Math.max(0,Number(r.value||0)-Number(r.paidValue||0));if(new Date(r.dueAt)<new Date(x.oldestDue))x.oldestDue=r.dueAt;dm.set(k,x)}const now=Date.now(),delinquents=[...dm.values()].map(x=>({...x,total:money(x.total),daysOverdue:Math.max(0,Math.floor((now-new Date(x.oldestDue).getTime())/86400000))})).sort((a,b)=>b.total-a.total);
  const fm=new Map();for(const r of active){const k=monthKey(r.dueAt);if(!k)continue;const x=fm.get(k)||{month:k,receitaPrevista:0,receitaRealizada:0,despesaPrevista:0,despesaRealizada:0};if(r.direction==='receivable'){x.receitaPrevista+=Number(r.value||0);if(r.status==='paid')x.receitaRealizada+=Number(r.paidValue||r.value||0)}else{x.despesaPrevista+=Number(r.value||0);if(r.status==='paid')x.despesaRealizada+=Number(r.paidValue||r.value||0)}fm.set(k,x)}const cashFlow=[...fm.values()].sort((a,b)=>a.month.localeCompare(b.month)).map(x=>({...x,receitaPrevista:money(x.receitaPrevista),receitaRealizada:money(x.receitaRealizada),despesaPrevista:money(x.despesaPrevista),despesaRealizada:money(x.despesaRealizada),saldoPrevisto:money(x.receitaPrevista-x.despesaPrevista),saldoRealizado:money(x.receitaRealizada-x.despesaRealizada)}));
  const cm=new Map();for(const r of active){const k=r.categoryName||'Sem categoria',x=cm.get(k)||{category:k,direction:r.direction,expected:0,realized:0};x.expected+=Number(r.value||0);if(r.status==='paid')x.realized+=Number(r.paidValue||r.value||0);cm.set(k,x)}const categories=[...cm.values()].map(x=>({...x,expected:money(x.expected),realized:money(x.realized)})).sort((a,b)=>b.expected-a.expected);
  const view=clean(q.view,30);let entries=base;if(view==='overdue')entries=base.filter(r=>r.status==='pending'&&dueView(r)==='overdue');else if(view==='upcoming')entries=base.filter(r=>r.status==='pending'&&dueView(r)==='upcoming');else if(view==='paid')entries=base.filter(r=>r.status==='paid');else if(view==='pending')entries=base.filter(r=>r.status==='pending');else if(view==='cancelled')entries=base.filter(r=>r.status==='cancelled');entries=entries.sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));return{summary:{receivables:{total:bucket(rec),pending:bucket(recPending),upcoming:bucket(recUpcoming),overdue:bucket(recOver),paid:{count:recPaid.length,value:sum(recPaid,'paidValue')}},payables:{total:bucket(pay),pending:bucket(payPending),upcoming:bucket(payUpcoming),overdue:bucket(payOver),paid:{count:payPaid.length,value:sum(payPaid,'paidValue')}},delinquentCustomers:delinquents.length},delinquents:delinquents.slice(0,500),cashFlow,categories,entries:entries.slice(0,2000).map(r=>({...r,view:dueView(r)}))}}
 async function sales(q={}){const{from,to}=reportPeriod(q),Historical=mongoose.models.ErpSigeHistoricalSale;const hist=Historical?await Historical.find({date:{$gte:from,$lte:to}}).sort({date:-1}).limit(20000).lean():[],current=await Order.find({origin:'erp_ariana',status:'faturado',updatedAt:{$gte:from,$lte:to}}).sort({updatedAt:-1}).limit(10000).lean(),rows=[];for(const s of hist){if(String(s.status||'').toLowerCase()==='canceled')continue;rows.push({id:String(s._id),source:'historico',code:s.code||'',date:s.date,customerName:s.customerName||'Consumidor',sellerName:s.sellerName||'',total:Number(s.total||0),paymentMethod:s.paymentCondition||'',items:(s.items||[]).map(i=>({name:i.description||'',productId:i.productId||'',qty:Number(i.quantity||0),value:Number(i.subtotal||0)}))})}for(const o of current)rows.push({id:String(o._id),source:'ariana',code:o.televendas?.erp?.code||'',date:o.updatedAt,customerName:o.customerName||'Consumidor',sellerName:o.televendas?.erp?.sellerName||o.sellerName||'',total:Number(o.total||0),paymentMethod:o.payment?.method||'',items:(o.items||[]).map(i=>({name:i.name||'',productId:String(i.productId||''),qty:Number(i.qty||0),value:Number(i.totalPrice||0)}))});const customers=new Map(),products=new Map(),sellers=new Map(),payments=new Map();let total=0,itemCount=0;for(const s of rows){total+=s.total;const ck=(s.customerName||'Consumidor').trim().toLowerCase(),c=customers.get(ck)||{name:s.customerName||'Consumidor',orders:0,value:0};c.orders++;c.value+=s.total;customers.set(ck,c);const sk=(s.sellerName||'Sem vendedor').trim().toLowerCase(),sv=sellers.get(sk)||{name:s.sellerName||'Sem vendedor',orders:0,value:0};sv.orders++;sv.value+=s.total;sellers.set(sk,sv);const pk=s.paymentMethod||'Não informado';payments.set(pk,(payments.get(pk)||0)+s.total);for(const i of s.items){itemCount+=i.qty;const key=i.productId||String(i.name||'produto').toLowerCase(),p=products.get(key)||{name:i.name||'Produto',qty:0,value:0};p.qty+=i.qty;p.value+=i.value;products.set(key,p)}}const ranking=[...customers.values()].sort((a,b)=>b.value-a.value).map(x=>({...x,value:money(x.value)}));let acc=0;const abc=ranking.map(x=>{acc+=x.value;const cumulative=total?acc/total:0;return{...x,share:total?money(x.value/total*100):0,curve:cumulative<=.8?'A':cumulative<=.95?'B':'C'}});return{period:{from,to},summary:{sales:rows.length,items:itemCount,total:money(total),averageTicket:rows.length?money(total/rows.length):0,historical:rows.filter(x=>x.source==='historico').length,current:rows.filter(x=>x.source==='ariana').length},customerRanking:ranking.slice(0,500),customerABC:abc.slice(0,1000),productRanking:[...products.values()].sort((a,b)=>b.value-a.value).slice(0,500).map(x=>({...x,value:money(x.value)})),sellerRanking:[...sellers.values()].sort((a,b)=>b.value-a.value).slice(0,200).map(x=>({...x,value:money(x.value)})),paymentMethods:Object.fromEntries([...payments].map(([k,v])=>[k,money(v)])),sales:rows.slice(0,2000).map(x=>({...x,total:money(x.total)}))}}
 return{finance,sales};
}
export default createErpParityAnalyticsService;
