import mongoose from 'mongoose';
import { getErpSettingsSnapshot } from './erpSettingsService.js';

const clean=(v='',m=500)=>String(v??'').trim().slice(0,m);
const digits=(v='')=>String(v??'').replace(/\D/g,'');
const esc=(v='')=>String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const fold=(v='')=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const UF_BY_CODE={12:'AC',27:'AL',16:'AP',13:'AM',29:'BA',23:'CE',53:'DF',32:'ES',52:'GO',21:'MA',51:'MT',50:'MS',31:'MG',15:'PA',25:'PB',41:'PR',26:'PE',22:'PI',33:'RJ',24:'RN',43:'RS',11:'RO',14:'RR',42:'SC',35:'SP',28:'SE',17:'TO'};
const UF_BY_NAME={ACRE:'AC',ALAGOAS:'AL',AMAPA:'AP',AMAZONAS:'AM',BAHIA:'BA',CEARA:'CE','DISTRITO FEDERAL':'DF','ESPIRITO SANTO':'ES',GOIAS:'GO',MARANHAO:'MA','MATO GROSSO':'MT','MATO GROSSO DO SUL':'MS','MINAS GERAIS':'MG',PARA:'PA',PARAIBA:'PB',PARANA:'PR',PERNAMBUCO:'PE',PIAUI:'PI','RIO DE JANEIRO':'RJ','RIO GRANDE DO NORTE':'RN','RIO GRANDE DO SUL':'RS',RONDONIA:'RO',RORAIMA:'RR','SANTA CATARINA':'SC','SAO PAULO':'SP',SERGIPE:'SE',TOCANTINS:'TO'};
const VALID_UFS=new Set(Object.values(UF_BY_CODE));
let sigeActiveRepairDone=false;

function fail(message,statusCode=400,code='ERP_PEOPLE_ERROR'){const e=new Error(message);e.statusCode=statusCode;e.code=code;return e}
function personModel(){const Person=mongoose.models.ErpPerson;if(!Person)throw fail('Cadastro comercial do ERP ainda não foi inicializado.',503,'ERP_PEOPLE_UNAVAILABLE');return Person}
async function ensureSigePeopleVisible(Person){if(sigeActiveRepairDone)return;await Person.updateMany({source:'sige',active:false,importedAt:{$exists:true}},{$set:{active:true,'metadata.activeRepair':'trash_title_import_bug_2026-09-11'}});sigeActiveRepairDone=true}
export function normalizeUf(value=''){const raw=clean(value,80).toUpperCase(),key=fold(raw);if(!raw)return'';if(UF_BY_CODE[raw])return UF_BY_CODE[raw];if(VALID_UFS.has(raw))return raw;return UF_BY_NAME[key]||''}
export function normalizeCustomerPhone(value=''){
  const raw=clean(value,80);
  if(!raw)return'';
  const number=digits(raw);
  if(!number)return'';
  if(raw.startsWith('+')){
    if(number.length<8||number.length>15)throw fail('Telefone internacional inválido. Use o formato +código do país + número (ex.: +1 201 328 2716).',400,'INVALID_INTERNATIONAL_PHONE');
    return`+${number}`;
  }
  return number.slice(0,20);
}
function normalizeAddress(a={}){const rawUf=a.stateCode??a.uf??a.codigoUf??a.codigoUF??a.state??a.estado;return{street:clean(a.street??a.logradouro,220),number:clean(a.number??a.numero,80),complement:clean(a.complement??a.complemento,220),neighborhood:clean(a.neighborhood??a.bairro,160),city:clean(a.city??a.municipio,160),cityCode:digits(a.cityCode??a.codigoMunicipio).slice(0,7),state:clean(a.state??a.estado,80),stateCode:normalizeUf(rawUf),zipCode:digits(a.zipCode??a.cep).slice(0,8),country:clean(a.country??a.pais??'Brasil',100),countryCode:clean(a.countryCode??a.codigoPais??'1058',30)}}
function addressText(a={}){return[a.street,a.number,a.neighborhood,a.city,a.stateCode||a.state].map(x=>clean(x,180)).filter(Boolean).join(', ')}
function personRow(p={}){const address=normalizeAddress(p.address||{});return{id:String(p._id||''),source:p.source||'',sourceId:p.sourceId||'',name:p.name||p.companyName||'',companyName:p.companyName||'',document:p.document||'',ie:p.ie||'',ieExempt:Boolean(p.ieExempt),email:p.email||'',phone:p.phone||'',personType:p.personType||'',roles:Array.isArray(p.roles)?p.roles:[],address,addressText:addressText(address),linkedUserId:p.linkedUserId?String(p.linkedUserId):'',active:p.active!==false}}
function userRow(u={}){return{id:`user:${String(u._id||'')}`,source:'site',sourceId:String(u._id||''),name:u.name||u.email||'Cliente',companyName:'',document:digits(u.cpf),ie:'',ieExempt:false,email:u.email||'',phone:digits(u.phone),personType:'Cliente do site',roles:['Cliente'],address:{city:u.city||'',stateCode:normalizeUf(u.uf||'')},addressText:[u.city,normalizeUf(u.uf||'')].filter(Boolean).join('/'),linkedUserId:String(u._id||''),active:u.isActive!==false}}
function keyOf(row={}){return row.document?`doc:${digits(row.document)}`:(row.email?`mail:${String(row.email).toLowerCase()}`:(row.phone?`tel:${digits(row.phone)}`:`id:${row.id}`))}
function validatePayload(payload={}){const name=clean(payload.name||payload.companyName,220);if(!name)throw fail('Informe o nome ou razão social do cliente.');const document=digits(payload.document);if(document&&![11,14].includes(document.length))throw fail('CPF/CNPJ deve ter 11 ou 14 dígitos.');const rawUf=clean(payload.address?.stateCode??payload.address?.uf??payload.address?.codigoUf??payload.address?.codigoUF,80);if(rawUf&&!normalizeUf(rawUf))throw fail('Informe uma UF brasileira válida (ex.: MG).');const a=normalizeAddress(payload.address||{});if(a.zipCode&&a.zipCode.length!==8)throw fail('CEP deve ter 8 dígitos.');if(a.cityCode&&a.cityCode.length!==7)throw fail('Código IBGE do município deve ter 7 dígitos.');return{name,companyName:clean(payload.companyName,220),document,ie:clean(payload.ie,80),ieExempt:Boolean(payload.ieExempt),email:clean(payload.email,320).toLowerCase(),phone:normalizeCustomerPhone(payload.phone),personType:clean(payload.personType|| (document.length===14?'Pessoa Jurídica':'Pessoa Física'),80),roles:Array.isArray(payload.roles)&&payload.roles.length?payload.roles.map(x=>clean(x,80)).filter(Boolean):['Cliente'],address:a,active:payload.active!==false}}
async function applyGeneralRules(data){const cfg=(await getErpSettingsSnapshot()).general||{};if(cfg.requireCustomerPhone&&!data.phone)throw fail('A configuração do ERP exige telefone no cadastro do cliente.',409,'CUSTOMER_PHONE_REQUIRED');if(cfg.documentOptional===false&&!data.document)throw fail('A configuração do ERP exige CPF/CNPJ no cadastro do cliente.',409,'CUSTOMER_DOCUMENT_REQUIRED');return data}

export function createErpPeopleService(context={}){
  const {User}=context;if(!User)throw new Error('[erp-people] User não informado');
  async function list(query={}){const Person=personModel();await ensureSigePeopleVisible(Person);const q=clean(query.q||query.search,160),limit=Math.min(200,Math.max(1,Number(query.limit||50)));const filter={active:{$ne:false}};if(q){const rx=new RegExp(esc(q),'i'),qd=digits(q);filter.$or=[{name:rx},{companyName:rx},{email:rx},{phone:rx},{document:rx}];if(qd)filter.$or.push({document:new RegExp(esc(qd),'i')},{phone:new RegExp(esc(qd),'i')})}const commercial=(await Person.find(filter).sort({name:1}).limit(limit).lean()).map(personRow);const seen=new Set(commercial.map(keyOf)),users=[];if(commercial.length<limit){const uf={role:'customer',isActive:{$ne:false}};if(q){const rx=new RegExp(esc(q),'i'),qd=digits(q);uf.$or=[{name:rx},{email:rx},{phone:rx},{cpf:rx}];if(qd)uf.$or.push({phone:new RegExp(esc(qd),'i')},{cpf:new RegExp(esc(qd),'i')})}const site=await User.find(uf).select('_id name email phone cpf city uf isActive').sort({name:1}).limit(limit).lean();for(const u of site){const row=userRow(u),k=keyOf(row);if(seen.has(k))continue;seen.add(k);users.push(row);if(commercial.length+users.length>=limit)break}}return{people:[...commercial,...users],count:commercial.length+users.length,commercialCount:commercial.length,siteOnlyCount:users.length}}
  async function get(id){const Person=personModel();await ensureSigePeopleVisible(Person);if(String(id).startsWith('user:')){const u=await User.findById(String(id).slice(5)).select('_id name email phone cpf city uf isActive').lean();if(!u)throw fail('Cliente não encontrado.',404,'CUSTOMER_NOT_FOUND');return userRow(u)}if(!mongoose.isValidObjectId(id))throw fail('Cliente não encontrado.',404,'CUSTOMER_NOT_FOUND');const p=await Person.findById(id).lean();if(!p)throw fail('Cliente não encontrado.',404,'CUSTOMER_NOT_FOUND');return personRow(p)}
  async function create(payload={},actor={}){const Person=personModel(),data=await applyGeneralRules(validatePayload(payload)),who=clean(actor.name||actor.nome||actor.email||'Operador',180);if(data.document){const exists=await Person.findOne({document:data.document,active:{$ne:false}}).lean();if(exists)throw fail('Já existe um cliente ativo com este CPF/CNPJ.',409,'CUSTOMER_DOCUMENT_EXISTS')}const sourceId=`manual_${new mongoose.Types.ObjectId()}`;const p=await Person.create({...data,source:'manual',sourceId,metadata:{createdBy:who,createdIn:'ariana_erp'},importedAt:null});return personRow(p.toObject())}
  async function update(id,payload={},actor={}){const Person=personModel(),data=await applyGeneralRules(validatePayload(payload)),who=clean(actor.name||actor.nome||actor.email||'Operador',180);let targetId=id;if(String(id).startsWith('user:')){const uid=String(id).slice(5),u=await User.findById(uid).select('_id name email phone cpf city uf isActive').lean();if(!u)throw fail('Cliente não encontrado.',404,'CUSTOMER_NOT_FOUND');let linked=await Person.findOne({linkedUserId:u._id,active:{$ne:false}});if(!linked){const p=await Person.create({...data,source:'manual',sourceId:`site_${uid}`,linkedUserId:u._id,metadata:{createdBy:who,createdIn:'ariana_erp',promotedFromSite:true}});return personRow(p.toObject())}targetId=String(linked._id)}if(!mongoose.isValidObjectId(targetId))throw fail('Cliente não encontrado.',404,'CUSTOMER_NOT_FOUND');if(data.document){const dup=await Person.findOne({_id:{$ne:targetId},document:data.document,active:{$ne:false}}).lean();if(dup)throw fail('Já existe outro cliente ativo com este CPF/CNPJ.',409,'CUSTOMER_DOCUMENT_EXISTS')}const p=await Person.findByIdAndUpdate(targetId,{$set:{...data,'metadata.updatedBy':who,'metadata.updatedIn':'ariana_erp'}},{new:true});if(!p)throw fail('Cliente não encontrado.',404,'CUSTOMER_NOT_FOUND');return personRow(p.toObject())}
  return{list,get,create,update};
}
export default createErpPeopleService;
