const clean=(v='',m=500)=>String(v??'').trim().slice(0,m);
const digits=(v='')=>String(v??'').replace(/\D/g,'');
function normalize(v=''){return clean(v,180).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function fail(message,statusCode=400,code='ERP_PRODUCT_ERROR'){const e=new Error(message);e.statusCode=statusCode;e.code=code;return e}
function fiscalFrom(specs={}){return{ncm:digits(specs.ncm).slice(0,8),cest:digits(specs.cest).slice(0,7),cfop:digits(specs.cfop).slice(0,4),unit:clean(specs.unit||specs.unidade||'UN',10).toUpperCase(),origin:clean(specs.productOrigin??specs.origin??'',2),csosn:digits(specs.csosn||specs.icmsCsosn).slice(0,3),icmsCst:digits(specs.icmsCst||specs.cstIcms).slice(0,3),pisCst:digits(specs.pisCst||specs.cstPis).slice(0,2),cofinsCst:digits(specs.cofinsCst||specs.cstCofins).slice(0,2),ean:digits(specs.ean||specs.barcode||specs.gtin).slice(0,14)}}
function validateFiscal(input={}){const f={ncm:digits(input.ncm).slice(0,8),cest:digits(input.cest).slice(0,7),cfop:digits(input.cfop).slice(0,4),unit:clean(input.unit||'UN',10).toUpperCase(),origin:clean(input.origin,2),csosn:digits(input.csosn).slice(0,3),icmsCst:digits(input.icmsCst).slice(0,3),pisCst:digits(input.pisCst).slice(0,2),cofinsCst:digits(input.cofinsCst).slice(0,2),ean:digits(input.ean).slice(0,14)};if(input.ncm&&f.ncm.length!==8)throw fail('NCM deve conter exatamente 8 dígitos.');if(input.cest&&f.cest.length!==7)throw fail('CEST deve conter 7 dígitos.');if(input.cfop&&f.cfop.length!==4)throw fail('CFOP deve conter 4 dígitos.');if(f.origin&&!/^[0-8]$/.test(f.origin))throw fail('Origem fiscal deve ser um código de 0 a 8.');if(input.csosn&&f.csosn.length!==3)throw fail('CSOSN deve conter 3 dígitos.');if(input.pisCst&&f.pisCst.length!==2)throw fail('CST PIS deve conter 2 dígitos.');if(input.cofinsCst&&f.cofinsCst.length!==2)throw fail('CST COFINS deve conter 2 dígitos.');return f}
export function createErpProductService(context={}){
 const {Product,toJSON}=context;if(!Product)throw new Error('[erp-products] Product não informado');
 const allowed=new Set(['ariana','ariana_moveis','arianamoveis','ariana_moveis_oficial','loja_ariana','marcelo_nunes_silva',...String(process.env.SIGE_ARIANA_SELLER_KEYS||process.env.ARIANA_SELLER_KEYS||'').split(',').map(normalize).filter(Boolean)]);
 function accepted(v=''){const key=normalize(v);return Boolean(key&&(allowed.has(key)||key==='ariana_moveis'||key==='arianamoveis'||(key.includes('ariana')&&key.includes('move'))))}
 function own(product={}){const sellerId=clean(product.sellerId||'',180),sellerName=clean(product.sellerName||'',180);if(!sellerId&&!sellerName)return true;if(sellerName)return accepted(sellerName)||accepted(sellerId);return accepted(sellerId)}
 const serial=d=>typeof toJSON==='function'?toJSON(d):(d?.toObject?d.toObject():d);
 function present(doc){const p=serial(doc),specs=p.specs||{};return{id:String(p._id||p.id),name:p.name||'',sku:p.sku||'',description:p.description||'',brand:p.brand||'',category:p.categoryName||p.category||'',price:Number(p.price||0),pixPrice:Number(p.pixPrice??p.price??0),stock:Number(p.stock||0),active:p.active!==false,image:p.imageUrl||p.mainImageUrl||p.image||p.imagem||'',sellerId:p.sellerId||'',sellerName:p.sellerName||'',specs,fiscal:fiscalFrom(specs)}}
 async function assertOwn(id){let p=null;try{p=await Product.findById(id)}catch{}if(!p)throw fail('Produto não encontrado.',404,'PRODUCT_NOT_FOUND');if(!own(p))throw fail('Este produto pertence a seller/fabricante externo e não pode ser alterado pelo cadastro físico da Ariana.',409,'EXTERNAL_SELLER_PRODUCT');return p}
 async function assertItems(items=[]){if(!Array.isArray(items)||!items.length)return true;const ids=[...new Set(items.map(i=>clean(i?.productId||i?.id||i?._id||'',120)).filter(Boolean))];for(const id of ids){const p=await assertOwn(id);if(p.active===false)throw fail('Produto não encontrado ou inativo.',409,'PRODUCT_UNAVAILABLE')}return true}
 async function list(query={}){const limit=Math.min(200,Math.max(1,Number(query.limit||40))),q=clean(query.q||query.search||'',140),filter={};if(query.includeInactive!=='1')filter.active={$ne:false};if(q){const rx=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');filter.$or=[{name:rx},{sku:rx},{brand:rx},{category:rx},{categoryName:rx}]}const docs=await Product.find(filter).sort({name:1}).limit(Math.max(limit*4,160));return docs.filter(own).slice(0,limit).map(present)}
 async function get(id){return present(await assertOwn(id))}
 async function create(payload={}){const name=clean(payload.name,260);if(!name)throw fail('Informe o nome do produto.');const sku=clean(payload.sku,120);if(sku){const dup=await Product.findOne({sku});if(dup)throw fail('Já existe um produto com este SKU/código.',409,'PRODUCT_SKU_EXISTS')}const f=validateFiscal(payload.fiscal||payload),specs={...(payload.specs||{}),ncm:f.ncm,cest:f.cest,cfop:f.cfop,unit:f.unit,productOrigin:f.origin,csosn:f.csosn,icmsCst:f.icmsCst,pisCst:f.pisCst,cofinsCst:f.cofinsCst,ean:f.ean};const p=await Product.create({sellerName:'Ariana Móveis',name,sku,description:clean(payload.description,5000),brand:clean(payload.brand,160),category:clean(payload.category,180),price:Math.max(0,Number(payload.price||0)),pixPrice:payload.pixPrice===''||payload.pixPrice==null?null:Math.max(0,Number(payload.pixPrice||0)),stock:Math.max(0,Number(payload.stock||0)),active:payload.active!==false,specs});return present(p)}
 async function update(id,payload={}){const p=await assertOwn(id),name=clean(payload.name??p.name,260);if(!name)throw fail('Informe o nome do produto.');const sku=clean(payload.sku??p.sku,120);if(sku){const dup=await Product.findOne({_id:{$ne:p._id},sku});if(dup)throw fail('Já existe outro produto com este SKU/código.',409,'PRODUCT_SKU_EXISTS')}const existing=p.specs&&typeof p.specs==='object'?p.specs:{},inputFiscal=payload.fiscal||payload,f=validateFiscal({...fiscalFrom(existing),...inputFiscal});p.name=name;p.sku=sku;p.description=clean(payload.description??p.description,5000);p.brand=clean(payload.brand??p.brand,160);p.category=clean(payload.category??p.categoryName??p.category,180);if(payload.price!==undefined)p.price=Math.max(0,Number(payload.price||0));if(payload.pixPrice!==undefined)p.pixPrice=payload.pixPrice===''||payload.pixPrice==null?null:Math.max(0,Number(payload.pixPrice||0));if(payload.stock!==undefined)p.stock=Math.max(0,Number(payload.stock||0));if(payload.active!==undefined)p.active=Boolean(payload.active);p.specs={...existing,ncm:f.ncm,cest:f.cest,cfop:f.cfop,unit:f.unit,productOrigin:f.origin,csosn:f.csosn,icmsCst:f.icmsCst,pisCst:f.pisCst,cofinsCst:f.cofinsCst,ean:f.ean};await p.save();return present(p)}
 return{assertItems,list,get,create,update,isOwnProduct:own}
}
export default createErpProductService;
