import mongoose from 'mongoose';

const clean=(v='',m=500)=>String(v??'').trim().slice(0,m);
const money=v=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
const arr=v=>Array.isArray(v)?v:[];
const base={timestamps:true,versionKey:false,minimize:false};
function fail(message,statusCode=400,code='ERP_PURCHASE_ERROR'){const e=new Error(message);e.statusCode=statusCode;e.code=code;return e}
function actorName(a={}){return clean(a.name||a.email||'Administrador',180)}
function oid(Product,id){try{return new Product.db.base.Types.ObjectId(id)}catch{return null}}

const supplierSchema=new mongoose.Schema({
  name:{type:String,required:true,index:true},tradeName:{type:String,default:''},document:{type:String,default:'',index:true},
  email:{type:String,default:''},phone:{type:String,default:''},contactName:{type:String,default:''},city:{type:String,default:''},uf:{type:String,default:''},
  active:{type:Boolean,default:true,index:true},notes:{type:String,default:''},createdBy:{type:String,default:''},updatedBy:{type:String,default:''}
},base);
const purchaseItemSchema=new mongoose.Schema({productId:{type:String,required:true,index:true},name:String,sku:String,quantity:Number,unitCost:Number,lineTotal:Number,landedUnitCost:Number},{_id:false});
const purchaseSchema=new mongoose.Schema({
  number:{type:String,required:true,unique:true,index:true},supplierId:{type:String,required:true,index:true},supplierName:{type:String,required:true,index:true},supplierDocument:{type:String,default:''},
  status:{type:String,enum:['draft','ordered','received','cancelled'],default:'draft',index:true},issuedAt:{type:Date,default:Date.now,index:true},expectedAt:{type:Date,default:null},receivedAt:{type:Date,default:null,index:true},
  invoiceNumber:{type:String,default:''},invoiceKey:{type:String,default:'',index:true},items:{type:[purchaseItemSchema],default:[]},subtotal:{type:Number,default:0},freight:{type:Number,default:0},otherExpenses:{type:Number,default:0},total:{type:Number,default:0},
  notes:{type:String,default:''},createdBy:{type:String,default:''},updatedBy:{type:String,default:''},receivedBy:{type:String,default:''},stockApplied:{type:Boolean,default:false},costApplied:{type:Boolean,default:false}
},base);
const Supplier=mongoose.models.ErpSupplier||mongoose.model('ErpSupplier',supplierSchema);
const Purchase=mongoose.models.ErpPurchase||mongoose.model('ErpPurchase',purchaseSchema);

export function createErpPurchaseService(context={}){
  const Product=context.Product||mongoose.models.Product;if(!Product)throw new Error('[erp-purchases] Product não informado');
  async function nextNumber(){const y=new Date().getFullYear(),from=new Date(y,0,1),to=new Date(y+1,0,1),n=await Purchase.countDocuments({createdAt:{$gte:from,$lt:to}});return`CMP-${y}-${String(n+1).padStart(6,'0')}`}
  async function listSuppliers(q={}){const filter={};if(q.active==='true')filter.active=true;if(q.active==='false')filter.active=false;const text=clean(q.q||q.search,160);if(text){const rx=new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');filter.$or=[{name:rx},{tradeName:rx},{document:rx},{email:rx},{phone:rx}]};return Supplier.find(filter).sort({name:1}).limit(5000).lean()}
  async function saveSupplier(payload={},actor={}){const name=clean(payload.name,220);if(!name)throw fail('Informe o nome do fornecedor.');const document=clean(payload.document,30);if(document){const exists=await Supplier.findOne({document,_id:payload.id?{$ne:payload.id}:{$exists:true}}).lean().catch(()=>null);if(exists)throw fail('Já existe um fornecedor com este CPF/CNPJ.',409,'SUPPLIER_DOCUMENT_EXISTS')};const data={name,tradeName:clean(payload.tradeName,220),document,email:clean(payload.email,180),phone:clean(payload.phone,80),contactName:clean(payload.contactName,180),city:clean(payload.city,120),uf:clean(payload.uf,2).toUpperCase(),active:payload.active!==false,notes:clean(payload.notes,1000),updatedBy:actorName(actor)};if(payload.id){const row=await Supplier.findByIdAndUpdate(payload.id,{$set:data},{new:true}).lean();if(!row)throw fail('Fornecedor não encontrado.',404);return row}return Supplier.create({...data,createdBy:actorName(actor)})}
  async function getSupplier(id){const row=await Supplier.findById(id).lean().catch(()=>null);if(!row)throw fail('Fornecedor não encontrado.',404);return row}
  async function listPurchases(q={}){const filter={};if(q.status&&q.status!=='all')filter.status=clean(q.status,30);if(q.supplierId)filter.supplierId=clean(q.supplierId,80);if(q.from||q.to){filter.issuedAt={};if(q.from){const d=new Date(q.from);d.setHours(0,0,0,0);filter.issuedAt.$gte=d}if(q.to){const d=new Date(q.to);d.setHours(23,59,59,999);filter.issuedAt.$lte=d}}const text=clean(q.q||q.search,160);if(text){const rx=new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');filter.$or=[{number:rx},{supplierName:rx},{supplierDocument:rx},{invoiceNumber:rx},{invoiceKey:rx}]};return Purchase.find(filter).sort({issuedAt:-1,createdAt:-1}).limit(5000).lean()}
  async function getPurchase(id){const row=await Purchase.findById(id).lean().catch(()=>null);if(!row)throw fail('Compra não encontrada.',404);return row}
  async function normalizeItems(items=[]){if(!arr(items).length)throw fail('Adicione pelo menos um produto à compra.');if(items.length>500)throw fail('A compra aceita no máximo 500 itens.');const ids=items.map(i=>oid(Product,i.productId));if(ids.some(x=>!x))throw fail('Existe produto inválido na compra.');const docs=await Product.collection.find({_id:{$in:ids}}).toArray(),map=new Map(docs.map(p=>[String(p._id),p]));return items.map(i=>{const p=map.get(String(i.productId));if(!p||p.active===false)throw fail(`Produto não encontrado ou inativo: ${clean(i.name||i.productId,120)}`,404,'PRODUCT_NOT_FOUND');const quantity=Math.max(1,Math.floor(Number(i.quantity||i.qty||0))),unitCost=money(i.unitCost??i.costPrice??0);if(!Number.isFinite(unitCost)||unitCost<0)throw fail(`Custo inválido para ${p.name}.`);return{productId:String(p._id),name:p.name||'',sku:p.sku||'',quantity,unitCost,lineTotal:money(quantity*unitCost),landedUnitCost:unitCost}})}
  async function createPurchase(payload={},actor={}){const supplier=await getSupplier(payload.supplierId),items=await normalizeItems(payload.items),subtotal=money(items.reduce((s,i)=>s+i.lineTotal,0)),freight=Math.max(0,money(payload.freight||0)),otherExpenses=Math.max(0,money(payload.otherExpenses||0));const number=clean(payload.number,50)||await nextNumber();const row=await Purchase.create({number,supplierId:String(supplier._id),supplierName:supplier.name,supplierDocument:supplier.document||'',status:['draft','ordered'].includes(payload.status)?payload.status:'draft',issuedAt:payload.issuedAt?new Date(payload.issuedAt):new Date(),expectedAt:payload.expectedAt?new Date(payload.expectedAt):null,invoiceNumber:clean(payload.invoiceNumber,80),invoiceKey:clean(payload.invoiceKey,80),items,subtotal,freight,otherExpenses,total:money(subtotal+freight+otherExpenses),notes:clean(payload.notes,1500),createdBy:actorName(actor),updatedBy:actorName(actor)});return row.toObject()}
  async function updatePurchase(id,payload={},actor={}){const current=await Purchase.findById(id);if(!current)throw fail('Compra não encontrada.',404);if(['received','cancelled'].includes(current.status))throw fail('Compra recebida ou cancelada não pode mais ser editada.',409,'PURCHASE_CLOSED');const supplier=payload.supplierId?await getSupplier(payload.supplierId):null,items=payload.items?await normalizeItems(payload.items):current.items.map(i=>i.toObject?i.toObject():i);const subtotal=money(items.reduce((s,i)=>s+Number(i.lineTotal||0),0)),freight=Math.max(0,money(payload.freight??current.freight)),otherExpenses=Math.max(0,money(payload.otherExpenses??current.otherExpenses));Object.assign(current,{supplierId:supplier?String(supplier._id):current.supplierId,supplierName:supplier?supplier.name:current.supplierName,supplierDocument:supplier?(supplier.document||''):current.supplierDocument,status:['draft','ordered'].includes(payload.status)?payload.status:current.status,issuedAt:payload.issuedAt?new Date(payload.issuedAt):current.issuedAt,expectedAt:payload.expectedAt?new Date(payload.expectedAt):current.expectedAt,invoiceNumber:payload.invoiceNumber!==undefined?clean(payload.invoiceNumber,80):current.invoiceNumber,invoiceKey:payload.invoiceKey!==undefined?clean(payload.invoiceKey,80):current.invoiceKey,items,subtotal,freight,otherExpenses,total:money(subtotal+freight+otherExpenses),notes:payload.notes!==undefined?clean(payload.notes,1500):current.notes,updatedBy:actorName(actor)});await current.save();return current.toObject()}
  async function receivePurchase(id,payload={},actor={}){const p=await Purchase.findById(id);if(!p)throw fail('Compra não encontrada.',404);if(p.status==='received'||p.stockApplied)throw fail('Esta compra já foi recebida.',409,'PURCHASE_ALREADY_RECEIVED');if(p.status==='cancelled')throw fail('Compra cancelada não pode ser recebida.',409,'PURCHASE_CANCELLED');const items=await normalizeItems(p.items.map(i=>i.toObject?i.toObject():i)),subtotal=money(items.reduce((s,i)=>s+i.lineTotal,0)),extras=money(Number(p.freight||0)+Number(p.otherExpenses||0)),totalQty=items.reduce((s,i)=>s+i.quantity,0);for(const i of items){const share=subtotal>0?i.lineTotal/subtotal:(i.quantity/Math.max(1,totalQty)),allocated=money(extras*share);i.landedUnitCost=money(i.unitCost+(allocated/i.quantity))}
    const ids=items.map(i=>oid(Product,i.productId)),docs=await Product.collection.find({_id:{$in:ids}},{projection:{_id:1,name:1,sku:1,stock:1}}).toArray(),beforeMap=new Map(docs.map(d=>[String(d._id),Number(d.stock||0)])),by=actorName(actor),stamp=payload.receivedAt?new Date(payload.receivedAt):new Date();
    const ops=items.map(i=>({updateOne:{filter:{_id:oid(Product,i.productId)},update:{$inc:{stock:i.quantity},$set:{costPrice:i.landedUnitCost,costSource:'purchase_receipt',costNotes:`Compra ${p.number} • ${p.supplierName}`,costUpdatedAt:stamp,costUpdatedBy:by}}}}));await Product.collection.bulkWrite(ops,{ordered:true});
    const Movement=mongoose.models.ErpStockMovement;if(Movement){await Movement.insertMany(items.map(i=>({productId:i.productId,productName:i.name,sku:i.sku,type:'entrada',quantity:i.quantity,before:beforeMap.get(i.productId)||0,after:(beforeMap.get(i.productId)||0)+i.quantity,reason:`Recebimento da compra ${p.number} - ${p.supplierName}`,reference:p.number,operatorName:by})),{ordered:false}).catch(()=>{})}
    p.items=items;p.subtotal=subtotal;p.total=money(subtotal+Number(p.freight||0)+Number(p.otherExpenses||0));p.status='received';p.receivedAt=stamp;p.receivedBy=by;p.updatedBy=by;p.stockApplied=true;p.costApplied=true;if(payload.invoiceNumber!==undefined)p.invoiceNumber=clean(payload.invoiceNumber,80);if(payload.invoiceKey!==undefined)p.invoiceKey=clean(payload.invoiceKey,80);await p.save();return p.toObject()}
  async function cancelPurchase(id,actor={}){const p=await Purchase.findById(id);if(!p)throw fail('Compra não encontrada.',404);if(p.status==='received'||p.stockApplied)throw fail('Compra já recebida não pode ser cancelada por esta rotina.',409,'PURCHASE_ALREADY_RECEIVED');p.status='cancelled';p.updatedBy=actorName(actor);await p.save();return p.toObject()}
  return{listSuppliers,saveSupplier,listPurchases,getPurchase,createPurchase,updatePurchase,receivePurchase,cancelPurchase};
}
export default createErpPurchaseService;
