import crypto from 'crypto';
import mongoose from 'mongoose';
import { extractCsvFilesFromZip, parseCsvBuffer } from './erpSigeMigrationService.js';

const clean=(v='',m=2000)=>String(v??'').trim().slice(0,m);
const norm=(v='')=>clean(v,500).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const digits=(v='')=>String(v??'').replace(/\D/g,'');
const num=(v=0)=>{const s=String(v??'').trim();if(!s)return 0;const n=Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s);return Number.isFinite(n)?n:0};
const money=v=>Math.round((num(v)+Number.EPSILON)*100)/100;
const yes=v=>['1','true','sim','yes'].includes(String(v??'').trim().toLowerCase());
const dt=v=>{const d=new Date(clean(v,100));return Number.isNaN(d.getTime())?null:d};
const chunks=(a,n=500)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,(i+1)*n));
const rows=(files,names)=>names.flatMap(n=>files.has(n)?parseCsvBuffer(files.get(n)):[]);
function data(file){const f=extractCsvFilesFromZip(file.buffer);return{sales:rows(f,['vendas_pedidos.csv','vendas.csv']),items:rows(f,['itens_vendas.csv','itens_venda.csv']),entries:rows(f,['contas_pagar_receber.csv','contas_receber.csv','contas_pagar.csv']),payments:rows(f,['pagamentos_baixas.csv','pagamentos.csv'])}}
function group(a,k){const m=new Map();for(const r of a){const id=clean(r[k],120);if(!id)continue;if(!m.has(id))m.set(id,[]);m.get(id).push(r)}return m}
function dup(a){const s=new Set(),d=new Set();for(const r of a){const id=clean(r.Id,120);if(!id)continue;s.has(id)?d.add(id):s.add(id)}return d.size}
async function bulk(model,ops,n=500){let upserted=0,matched=0;for(const part of chunks(ops,n)){if(!part.length)continue;const r=await model.bulkWrite(part,{ordered:false});upserted+=Number(r.upsertedCount||0);matched+=Number(r.matchedCount||0)}return{upserted,matched}}

const saleSchema=new mongoose.Schema({sourceSystem:{type:String,default:'sige'},sourceId:{type:String,required:true,index:true},code:String,customerSourceId:String,customerName:String,customerDocument:String,date:Date,status:String,billed:Boolean,sellerName:String,subtotal:Number,shipping:Number,total:Number,paymentCondition:String,invoiceNumber:String,invoiceSerie:String,invoiceStatus:String,items:[mongoose.Schema.Types.Mixed],metadata:mongoose.Schema.Types.Mixed},{timestamps:true,versionKey:false,minimize:false});saleSchema.index({sourceSystem:1,sourceId:1},{unique:true});
const paySchema=new mongoose.Schema({sourceSystem:{type:String,default:'sige'},sourceId:{type:String,required:true,index:true},entrySourceId:{type:String,index:true},paymentDate:Date,paymentMethod:String,bankSourceId:String,bankAccountId:String,bankAccountName:String,value:Number,discounts:Number,increases:Number,paidValue:Number},{timestamps:true,versionKey:false});paySchema.index({sourceSystem:1,sourceId:1},{unique:true});
const runSchema=new mongoose.Schema({source:String,packageName:String,packageSha256:String,scope:String,status:String,stats:mongoose.Schema.Types.Mixed,warnings:[String],actor:String,startedAt:Date,finishedAt:Date},{timestamps:true,versionKey:false,minimize:false});
const mapSchema=new mongoose.Schema({source:String,entityType:String,sourceId:String,targetModel:String,targetId:String,matchType:String,details:mongoose.Schema.Types.Mixed,importedAt:Date},{timestamps:true,versionKey:false,minimize:false});
const SaleHistory=mongoose.models.ErpSigeSaleHistory||mongoose.model('ErpSigeSaleHistory',saleSchema);
const PaymentHistory=mongoose.models.ErpSigePaymentHistory||mongoose.model('ErpSigePaymentHistory',paySchema);
const Run=mongoose.models.ErpMigrationRun||mongoose.model('ErpMigrationRun',runSchema);
const MapModel=mongoose.models.ErpMigrationMap||mongoose.model('ErpMigrationMap',mapSchema);
async function mapFor(type){const a=await MapModel.find({source:'sige',entityType:type}).select('sourceId targetId').lean();return new Map(a.map(x=>[String(x.sourceId),String(x.targetId)]))}

export function createErpSigeHistoryImportService(context={}){
  const Entry=mongoose.models.ErpFinancialEntry;
  if(!Entry)throw new Error('[erp-sige-history] ErpFinancialEntry não inicializado');
  async function preview(file){if(!file?.buffer)throw new Error('Selecione o ZIP da Etapa 2.');const d=data(file);const [pm,cm,bm]=await Promise.all([mapFor('product'),mapFor('account_category'),mapFor('bank_account')]);const saleIds=new Set(d.sales.map(x=>clean(x.Id,120))),entryIds=new Set(d.entries.map(x=>clean(x.Id,120)));let itemWithoutProductMap=0,entrySaleMissing=0,paymentEntryMissing=0;for(const x of d.items)if(clean(x.ProductId,120)&&!pm.has(clean(x.ProductId,120)))itemWithoutProductMap++;for(const x of d.entries)if(clean(x.SaleID,120)&&!saleIds.has(clean(x.SaleID,120)))entrySaleMissing++;for(const x of d.payments)if(clean(x.EntryId,120)&&!entryIds.has(clean(x.EntryId,120)))paymentEntryMissing++;const duplicates={sales:dup(d.sales),entries:dup(d.entries),payments:dup(d.payments)};return{counts:{sales:d.sales.length,saleItems:d.items.length,financialEntries:d.entries.length,receivables:d.entries.filter(x=>norm(x.Type)==='income').length,payables:d.entries.filter(x=>norm(x.Type)==='expense').length,payments:d.payments.length},links:{itemWithoutProductMap,entrySaleMissing,paymentEntryMissing},availableMaps:{products:pm.size,categories:cm.size,banks:bm.size},duplicates,safeForImport:!duplicates.sales&&!duplicates.entries&&!duplicates.payments&&!paymentEntryMissing,warnings:[itemWithoutProductMap?`${itemWithoutProductMap} item(ns) manterão referência histórica até a revisão dos produtos.`:'',entrySaleMissing?`${entrySaleMissing} lançamento(s) serão preservados sem inventar venda ausente.`:''].filter(Boolean)}}

  async function importHistory(file,confirmation,actor={}){if(confirmation!=='IMPORTAR_HISTORICO_SIGE')throw Object.assign(new Error('Confirmação da Etapa 2 inválida.'),{statusCode:409});if(!file?.buffer)throw new Error('Selecione o ZIP da Etapa 2.');const d=data(file),sha=crypto.createHash('sha256').update(file.buffer).digest('hex');const run=await Run.create({source:'sige',packageName:clean(file.originalname||'sige_historico.zip',255),packageSha256:sha,scope:'history-sales-finance',status:'running',stats:{phase:'starting'},warnings:[],actor:clean(actor.name||actor.email||'Administrador',180),startedAt:new Date()});try{const [pm,cm,bm]=await Promise.all([mapFor('product'),mapFor('account_category'),mapFor('bank_account')]);const ig=group(d.items,'SaleId'),pg=group(d.payments,'EntryId');
    const salesOps=d.sales.filter(x=>clean(x.Id,120)).map(s=>{const sid=clean(s.Id,120),its=ig.get(sid)||[];return{updateOne:{filter:{sourceSystem:'sige',sourceId:sid},update:{$set:{code:clean(s.Code,100),customerSourceId:clean(s.CustomerId,120),customerName:clean(s.CustomerName,220),customerDocument:digits(s.CustomerCpfCnpj),date:dt(s.Date)||dt(s.CreatedAt),status:clean(s.NegociationStatus,120),billed:yes(s.Billed),sellerName:clean(s.SellerName,180),subtotal:money(s.SubTotal),shipping:money(s.ShippingValue),total:money(s.Total),paymentCondition:clean(s.PaymentCondition,160),invoiceNumber:clean(s.InvoiceNumber,80),invoiceSerie:clean(s.InvoiceSerie,40),invoiceStatus:clean(s.InvoiceStatus,120),items:its.map(i=>({sourceId:clean(i.Id,120),productSourceId:clean(i.ProductId,120),productId:pm.get(clean(i.ProductId,120))||'',description:clean(i.Description,300),quantity:num(i.Quantity),unitPrice:money(i.SalePrice),subtotal:money(i.SubTotalWithDiscount||i.SubTotal),cost:money(i.ValueCostTotal)})),metadata:{internalCode:clean(s.InternalCode,100),saleOrigin:clean(s.SaleOrigin,120),categoryName:clean(s.CategoryName,180),originalCreatedAt:dt(s.CreatedAt),originalUpdatedAt:dt(s.LastUpdate)}}},$setOnInsert:{sourceSystem:'sige',sourceId:sid}},upsert:true}}});const salesBulk=await bulk(SaleHistory,salesOps,300);run.stats={phase:'sales_completed',sales:{source:d.sales.length,...salesBulk}};await run.save();
    const entryOps=d.entries.filter(x=>clean(x.Id,120)).map(e=>{const sid=clean(e.Id,120),ps=pg.get(sid)||[],paidValue=money(ps.reduce((t,p)=>t+num(p.PaidValue||p.Value),0)),paid=yes(e.Paid),cancelled=Boolean(clean(e.TrashTitle)),cat=clean(e.AccountCategoryId,120),bank=clean(e.BankAccountId,120)||clean(ps.find(p=>p.BankAccountId)?.BankAccountId,120);return{updateOne:{filter:{sourceSystem:'sige',sourceId:sid},update:{$set:{direction:norm(e.Type)==='expense'?'payable':'receivable',personName:clean(e.PersonName,220)||'Cadastro histórico SIGE',personDocument:digits(e.PersonCpfCnpj),description:`SIGE ${clean(e.Code,80)||sid}`,categoryId:cm.get(cat)||'',categoryName:clean(e.AccountCategoryName,180),bankAccountId:bm.get(bank)||'',bankAccountName:clean(e.BankAccountName,180),paymentMethod:clean(e.PaymentMethod,100)||clean(ps[0]?.PaymentMethod,100),value:money(e.Value),advance:Math.max(0,money(e.EntranceValue)),competenceAt:dt(e.Date)||dt(e.CreatedAt)||new Date(),dueAt:dt(e.MaturityDate)||dt(e.Date)||new Date(),status:cancelled?'cancelled':paid?'paid':'pending',paidAt:paid?(dt(ps.at(-1)?.PaymentDate)||dt(e.LastUpdate)||dt(e.Date)):null,paidValue:paid?(paidValue||money(e.Value)):paidValue,notes:'Importado do SIGE; saldo bancário atual não é recalculado retroativamente.',origin:'sige_import',orderId:'',sourceSystem:'sige',sourceId:sid,migration:{sourcePersonId:clean(e.PersonId,120),sourceCategoryId:cat,sourceBankAccountId:bank,sourceSaleId:clean(e.SaleID,120),relationshipType:clean(e.RelationshipType,120)}},$setOnInsert:{createdBy:'Migração SIGE',createdAt:dt(e.CreatedAt)||dt(e.Date)||new Date()}},upsert:true}}});const entryBulk=await bulk(Entry.collection,entryOps,400);
    const payOps=d.payments.filter(x=>clean(x.Id,120)).map(p=>({updateOne:{filter:{sourceSystem:'sige',sourceId:clean(p.Id,120)},update:{$set:{entrySourceId:clean(p.EntryId,120),paymentDate:dt(p.PaymentDate),paymentMethod:clean(p.PaymentMethod,100),bankSourceId:clean(p.BankAccountId,120),bankAccountId:bm.get(clean(p.BankAccountId,120))||'',bankAccountName:clean(p.BankAccountName,180),value:money(p.Value),discounts:money(p.Discounts),increases:money(p.Increases),paidValue:money(p.PaidValue)},$setOnInsert:{sourceSystem:'sige',sourceId:clean(p.Id,120)}},upsert:true}}));const payBulk=await bulk(PaymentHistory,payOps,500);const sourceSaleIds=new Set(d.sales.map(s=>clean(s.Id,120)));const missingSales=d.entries.filter(e=>clean(e.SaleID,120)&&!sourceSaleIds.has(clean(e.SaleID,120))).length,unmappedItems=d.items.filter(i=>clean(i.ProductId,120)&&!pm.has(clean(i.ProductId,120))).length;const stats={phase:'completed',sales:{source:d.sales.length,...salesBulk},saleItems:d.items.length,financial:{source:d.entries.length,...entryBulk,receivables:d.entries.filter(x=>norm(x.Type)==='income').length,payables:d.entries.filter(x=>norm(x.Type)==='expense').length},payments:{source:d.payments.length,...payBulk},unmappedSaleItems:unmappedItems,financialWithoutSale:missingSales};const warnings=[];if(unmappedItems)warnings.push(`${unmappedItems} item(ns) ficaram com vínculo de produto pendente.`);if(missingSales)warnings.push(`${missingSales} lançamento(s) não têm venda de origem no pacote local.`);run.status='completed';run.stats=stats;run.warnings=warnings;run.finishedAt=new Date();await run.save();return{runId:String(run._id),status:'completed',stats,warnings,safety:{stockMoved:false,bankBalanceReplayed:false,fiscalDocumentsImported:false}}}catch(error){run.status='failed';run.warnings=[clean(error.message,1000)];run.finishedAt=new Date();await run.save().catch(()=>{});throw error}}

  async function status(){const latestRun=await Run.findOne({source:'sige',scope:'history-sales-finance'}).sort({createdAt:-1}).lean();const [sales,financialEntries,payments]=await Promise.all([SaleHistory.countDocuments({sourceSystem:'sige'}),Entry.collection.countDocuments({sourceSystem:'sige'}),PaymentHistory.countDocuments({sourceSystem:'sige'})]);return{latestRun,counts:{sales,financialEntries,payments}}}
  return{preview,importHistory,status};
}
export default createErpSigeHistoryImportService;
