import crypto from 'crypto';
import mongoose from 'mongoose';
import { extractCsvFilesFromZip, parseCsvBuffer } from './erpSigeMigrationService.js';

const clean=(v='',m=2000)=>String(v??'').trim().slice(0,m);
const norm=(v='')=>clean(v,500).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const digits=(v='')=>String(v??'').replace(/\D/g,'');
const yes=v=>['1','true','sim','yes'].includes(String(v??'').trim().toLowerCase());
const num=(v=0)=>{const s=String(v??'').trim();if(!s)return 0;const n=Number(s.includes(',')?s.replace(/\./g,'').replace(',','.'):s);return Number.isFinite(n)?n:0};
const money=v=>Math.round((num(v)+Number.EPSILON)*100)/100;
const dt=v=>{const s=clean(v,100);if(!s)return null;const d=new Date(s);return Number.isNaN(d.getTime())?null:d};
const chunks=(a,n=500)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,(i+1)*n));
function fail(message,statusCode=400,code='ERP_SIGE_HISTORY_ERROR'){const e=new Error(message);e.statusCode=statusCode;e.code=code;return e}
function rows(files,names){const out=[];for(const n of names){const b=files.get(n);if(b)out.push(...parseCsvBuffer(b))}return out}
function dataset(buffer){const f=extractCsvFilesFromZip(buffer);return{sales:rows(f,['vendas_pedidos.csv','vendas.csv']),items:rows(f,['itens_vendas.csv','itens_venda.csv']),entries:rows(f,['contas_pagar_receber.csv','contas_receber.csv','contas_pagar.csv']),payments:rows(f,['pagamentos_baixas.csv','pagamentos.csv'])}}
function groupBy(a,key){const m=new Map();for(const r of a){const k=clean(r[key],120);if(!k)continue;if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}
function duplicateIds(a){const seen=new Set(),dup=new Set();for(const r of a){const id=clean(r.Id,120);if(!id)continue;if(seen.has(id))dup.add(id);seen.add(id)}return dup.size}
async function bulk(model,ops,size=500){let upserted=0,matched=0,modified=0;for(const part of chunks(ops,size)){if(!part.length)continue;const r=await model.bulkWrite(part,{ordered:false});upserted+=Number(r.upsertedCount||0);matched+=Number(r.matchedCount||0);modified+=Number(r.modifiedCount||0)}return{upserted,matched,modified}}

const saleSchema=new mongoose.Schema({sourceSystem:{type:String,default:'sige',index:true},sourceId:{type:String,required:true,index:true},code:String,customerSourceId:String,customerName:{type:String,index:true},customerDocument:String,date:{type:Date,index:true},status:{type:String,index:true},billed:{type:Boolean,index:true},sellerName:{type:String,index:true},subtotal:Number,shipping:Number,total:Number,paymentCondition:String,invoiceNumber:String,invoiceSerie:String,invoiceStatus:String,items:[mongoose.Schema.Types.Mixed],metadata:mongoose.Schema.Types.Mixed},{timestamps:true,versionKey:false,minimize:false});
saleSchema.index({sourceSystem:1,sourceId:1},{unique:true});
const paymentSchema=new mongoose.Schema({sourceSystem:{type:String,default:'sige',index:true},sourceId:{type:String,required:true,index:true},entrySourceId:{type:String,index:true},paymentDate:{type:Date,index:true},paymentMethod:String,bankSourceId:String,bankAccountId:String,bankAccountName:String,value:Number,discounts:Number,increases:Number,paidValue:Number},{timestamps:true,versionKey:false});
paymentSchema.index({sourceSystem:1,sourceId:1},{unique:true});
const runSchema=new mongoose.Schema({source:{type:String,index:true},packageName:String,packageSha256:String,scope:{type:String,index:true},status:{type:String,index:true},stats:mongoose.Schema.Types.Mixed,warnings:[String],actor:String,startedAt:Date,finishedAt:Date},{timestamps:true,versionKey:false,minimize:false});
const mapSchema=new mongoose.Schema({source:String,entityType:String,sourceId:String,targetModel:String,targetId:String,matchType:String,details:mongoose.Schema.Types.Mixed,importedAt:Date},{timestamps:true,versionKey:false,minimize:false});
const SaleHistory=mongoose.models.ErpSigeHistoricalSale||mongoose.model('ErpSigeHistoricalSale',saleSchema);
const PaymentHistory=mongoose.models.ErpSigeHistoricalPayment||mongoose.model('ErpSigeHistoricalPayment',paymentSchema);
const Run=mongoose.models.ErpMigrationRun||mongoose.model('ErpMigrationRun',runSchema);
const MapModel=mongoose.models.ErpMigrationMap||mongoose.model('ErpMigrationMap',mapSchema);

async function migrationMap(type){const a=await MapModel.find({source:'sige',entityType:type}).select('sourceId targetId').lean();return new Map(a.map(x=>[String(x.sourceId),String(x.targetId)]))}

export function createErpSigeHistoryImportService(){
 const Entry=mongoose.models.ErpFinancialEntry;if(!Entry)throw new Error('[erp-sige-history] ErpFinancialEntry não inicializado');
 async function previewFile(file){if(!file?.buffer)throw fail('Selecione o ZIP da Etapa 2.');const d=dataset(file.buffer);const [pm,cm,bm]=await Promise.all([migrationMap('product'),migrationMap('account_category'),migrationMap('bank_account')]);const saleIds=new Set(d.sales.map(r=>clean(r.Id,120)).filter(Boolean)),entryIds=new Set(d.entries.map(r=>clean(r.Id,120)).filter(Boolean));const links={itemWithoutProductMap:d.items.filter(r=>clean(r.ProductId,120)&&!pm.has(clean(r.ProductId,120))).length,financialWithoutSale:d.entries.filter(r=>clean(r.SaleID,120)&&!saleIds.has(clean(r.SaleID,120))).length,paymentWithoutEntry:d.payments.filter(r=>clean(r.EntryId,120)&&!entryIds.has(clean(r.EntryId,120))).length};const duplicates={sales:duplicateIds(d.sales),financial:duplicateIds(d.entries),payments:duplicateIds(d.payments)};return{counts:{sales:d.sales.length,saleItems:d.items.length,financialEntries:d.entries.length,receivables:d.entries.filter(r=>norm(r.Type)==='income').length,payables:d.entries.filter(r=>norm(r.Type)==='expense').length,payments:d.payments.length},maps:{products:pm.size,categories:cm.size,banks:bm.size},links,duplicates,safeForImport:!duplicates.sales&&!duplicates.financial&&!duplicates.payments&&!links.paymentWithoutEntry,warnings:[links.itemWithoutProductMap?`${links.itemWithoutProductMap} item(ns) manterão vínculo de produto pendente.`:'',links.financialWithoutSale?`${links.financialWithoutSale} lançamento(s) serão preservados sem inventar venda ausente.`:''].filter(Boolean)}}
 async function process(buffer,runId){const run=await Run.findById(runId);try{const d=dataset(buffer);const [pm,cm,bm]=await Promise.all([migrationMap('product'),migrationMap('account_category'),migrationMap('bank_account')]);const items=groupBy(d.items,'SaleId'),payments=groupBy(d.payments,'EntryId');
   const saleOps=d.sales.filter(r=>clean(r.Id,120)).map(s=>{const sid=clean(s.Id,120);return{updateOne:{filter:{sourceSystem:'sige',sourceId:sid},update:{$set:{code:clean(s.Code,100),customerSourceId:clean(s.CustomerId,120),customerName:clean(s.CustomerName,220),customerDocument:digits(s.CustomerCpfCnpj),date:dt(s.Date)||dt(s.CreatedAt),status:clean(s.NegociationStatus,120),billed:yes(s.Billed),sellerName:clean(s.SellerName,180),subtotal:money(s.SubTotal),shipping:money(s.ShippingValue),total:money(s.Total),paymentCondition:clean(s.PaymentCondition,160),invoiceNumber:clean(s.InvoiceNumber,80),invoiceSerie:clean(s.InvoiceSerie,40),invoiceStatus:clean(s.InvoiceStatus,120),items:(items.get(sid)||[]).map(i=>({sourceId:clean(i.Id,120),productSourceId:clean(i.ProductId,120),productId:pm.get(clean(i.ProductId,120))||'',description:clean(i.Description,300),quantity:num(i.Quantity),unitPrice:money(i.SalePrice),subtotal:money(i.SubTotalWithDiscount||i.SubTotal),cost:money(i.ValueCostTotal)})),metadata:{internalCode:clean(s.InternalCode,100),saleOrigin:clean(s.SaleOrigin,120),categoryName:clean(s.CategoryName,180),originalCreatedAt:dt(s.CreatedAt),originalUpdatedAt:dt(s.LastUpdate)}},$setOnInsert:{sourceSystem:'sige',sourceId:sid}},upsert:true}}});
   const sb=await bulk(SaleHistory,saleOps,300);run.stats={phase:'sales_completed',sales:{source:d.sales.length,...sb}};await run.save();
   const entryOps=d.entries.filter(r=>clean(r.Id,120)).map(e=>{const sid=clean(e.Id,120),rel=payments.get(sid)||[],paid=yes(e.Paid),paidValue=money(rel.reduce((a,p)=>a+num(p.PaidValue||p.Value),0)),sourceCategory=clean(e.AccountCategoryId,120),sourceBank=clean(e.BankAccountId,120)||clean(rel.find(p=>p.BankAccountId)?.BankAccountId,120),payDates=rel.map(p=>dt(p.PaymentDate)).filter(Boolean).sort((a,b)=>b-a);return{updateOne:{filter:{sourceSystem:'sige',sourceId:sid},update:{$set:{direction:norm(e.Type)==='expense'?'payable':'receivable',personName:clean(e.PersonName,220)||'Cadastro histórico',personDocument:digits(e.PersonCpfCnpj),description:`SIGE ${clean(e.Code,80)||sid}`,categoryId:cm.get(sourceCategory)||'',categoryName:clean(e.AccountCategoryName,180),bankAccountId:bm.get(sourceBank)||'',bankAccountName:clean(e.BankAccountName,180),paymentMethod:clean(e.PaymentMethod,100)||clean(rel[0]?.PaymentMethod,100),value:money(e.Value),advance:Math.max(0,money(e.EntranceValue)),competenceAt:dt(e.Date)||dt(e.CreatedAt)||new Date(),dueAt:dt(e.MaturityDate)||dt(e.Date)||new Date(),status:paid?'paid':'pending',paidAt:paid?(payDates[0]||dt(e.LastUpdate)||dt(e.Date)):null,paidValue:paid?(paidValue||money(e.Value)):paidValue,notes:'Histórico migrado do sistema anterior. Saldo bancário não recalculado retroativamente.',origin:'sige_import',orderId:'',sourceSystem:'sige',sourceId:sid,migration:{sourcePersonId:clean(e.PersonId,120),sourceCategoryId:sourceCategory,sourceBankAccountId:sourceBank,sourceSaleId:clean(e.SaleID,120),relationshipType:clean(e.RelationshipType,120)}},$setOnInsert:{createdBy:'Migração histórica',createdAt:dt(e.CreatedAt)||dt(e.Date)||new Date()}},upsert:true}}});
   const eb=await bulk(Entry.collection,entryOps,400);run.stats={phase:'financial_completed',sales:{source:d.sales.length,...sb},financial:{source:d.entries.length,...eb}};await run.save();
   const payOps=d.payments.filter(r=>clean(r.Id,120)).map(p=>{const sid=clean(p.Id,120),bank=clean(p.BankAccountId,120);return{updateOne:{filter:{sourceSystem:'sige',sourceId:sid},update:{$set:{entrySourceId:clean(p.EntryId,120),paymentDate:dt(p.PaymentDate),paymentMethod:clean(p.PaymentMethod,100),bankSourceId:bank,bankAccountId:bm.get(bank)||'',bankAccountName:clean(p.BankAccountName,180),value:money(p.Value),discounts:money(p.Discounts),increases:money(p.Increases),paidValue:money(p.PaidValue)},$setOnInsert:{sourceSystem:'sige',sourceId:sid}},upsert:true}}});
   const pb=await bulk(PaymentHistory,payOps,500);const sourceSaleIds=new Set(d.sales.map(s=>clean(s.Id,120)).filter(Boolean));const unmapped=d.items.filter(i=>clean(i.ProductId,120)&&!pm.has(clean(i.ProductId,120))).length,missing=d.entries.filter(e=>clean(e.SaleID,120)&&!sourceSaleIds.has(clean(e.SaleID,120))).length;run.status='completed';run.stats={phase:'completed',sales:{source:d.sales.length,...sb},saleItems:d.items.length,financial:{source:d.entries.length,...eb,receivables:d.entries.filter(r=>norm(r.Type)==='income').length,payables:d.entries.filter(r=>norm(r.Type)==='expense').length},payments:{source:d.payments.length,...pb},unmappedSaleItems:unmapped,financialWithoutSale:missing};run.warnings=[unmapped?`${unmapped} item(ns) ficaram com vínculo de produto pendente.`:'',missing?`${missing} lançamento(s) não têm venda de origem no pacote local.`:''].filter(Boolean);run.finishedAt=new Date();await run.save();
  }catch(error){run.status='failed';run.warnings=[clean(error.message,1000)];run.finishedAt=new Date();await run.save().catch(()=>{});console.error('[erp-sige-history/process]',error)} }
 async function startImport(file,confirmation,actor={}){if(confirmation!=='IMPORTAR_HISTORICO_SIGE')throw fail('Confirmação da Etapa 2 inválida.',409,'SIGE_HISTORY_CONFIRMATION_REQUIRED');const preview=await previewFile(file);if(!preview.safeForImport)throw fail('O pacote possui inconsistências que bloqueiam a importação automática.',409,'SIGE_HISTORY_NOT_SAFE');const sha=crypto.createHash('sha256').update(file.buffer).digest('hex');const existing=await Run.findOne({source:'sige',scope:'history-sales-finance',packageSha256:sha,status:'running'}).lean();if(existing)return{runId:String(existing._id),status:'running',reused:true};const run=await Run.create({source:'sige',packageName:clean(file.originalname||'sige_historico.zip',255),packageSha256:sha,scope:'history-sales-finance',status:'running',stats:{phase:'queued'},warnings:[],actor:clean(actor.name||actor.email||'Administrador',180),startedAt:new Date()});const buffer=Buffer.from(file.buffer);setImmediate(()=>process(buffer,String(run._id)));return{runId:String(run._id),status:'running',accepted:true,preview,safety:{stockMoved:false,bankBalanceReplayed:false,currentOrdersCreated:false,fiscalDocumentsImported:false}}}
 async function status(){const latestRun=await Run.findOne({source:'sige',scope:'history-sales-finance'}).sort({createdAt:-1}).lean();const [sales,financialEntries,payments]=await Promise.all([SaleHistory.countDocuments({sourceSystem:'sige'}),Entry.collection.countDocuments({sourceSystem:'sige'}),PaymentHistory.countDocuments({sourceSystem:'sige'})]);return{latestRun,counts:{sales,financialEntries,payments}}}
 return{preview:previewFile,startImport,status};
}
export default createErpSigeHistoryImportService;
